#! /bin/bash
# Aiko was here, improvising bash.

# -e means 'Exit immediately if a command exits with a non-zero status.'
set -e

# This sets our port to look for the creaturesengine
PORT=`cat ~/.creaturesengine/port`

#set the scripts array initially empty
scripts=();
cnt=0
PARM=7

# Here's the inject function:
	ject () {
		echo "$1"
		echo
		echo -n "$1"$'\r\nrscr\r\n' | nc localhost $PORT
		echo
	}
	
# Split up the scripts
	split-script () {
		delimiter=$'\n'scrp
		s=$1$delimiter
		while [[ $s ]]; do
			scripts+=( "${s%%"$delimiter"*}" );
			s=${s#*"$delimiter"};
		done;
		
		cnt=${#scripts[@]}

		#Now we need to add 'scrp' back to the begining of the scrps??
		# (but only if there's more than one... and not to the install)
		# (also: only if PARM actually is telling us to inject them)
		if [ $cnt -gt 1 ] && [ $(($PARM&2)) == 2 ]
			then
			#echo 'parsing scripts'
			for ((i=1;i<cnt;i++)); do
				scripts[i]=$'\r\ntarg null\r\n'"$delimiter${scripts[i]}"$'\r\ntarg null\r\n'
				echo "${scripts[i]}"
			done
		fi
		
		#This line is just to outs the scripts
		#declare -p scripts
	}

#This reads in the cosfile while stripping out all the comments
cosfile=`sed -e '/^*/d' "$1"`
#echo $cosfile

# Split the string into before and after rscr
# Note that this is case-sensitive. If your rscr is upper case... problems.

delimiter=$'\n'rscr
s=$cosfile$delimiter
array=();
while [[ $s ]]; do
    array+=( "${s%%"$delimiter"*}" );
    s=${s#*"$delimiter"};
done;
# declare -p array

# Check your parameter. If if doesn't exist, it's already assigned to 7
if [ $2 > 0 ]
	then
	PARM=$2
fi

# Some friendly translating of other parms should happen here
#(r = 1, s = 4, etc...)

#Here we parse the parameter which is gonna be similar to ject.
# so it has to do bitwise stuff. I always forget how bitwise
# stuff works.

#echo "parameter is"
#echo $PARM
#Check if you're removing first
if [ $(($PARM&1)) == 1 ]
then
	echo "remove script requested:"
	ject "${array[1]}"
fi

#Then check if you're injecting scripts
if [ $(($PARM&2)) == 2 ]
then
	echo "event scripts requested:"
	split-script "${array[0]}"
	#script inject here
	
	for ((i=1;i<cnt;i++)); do
		echo "${scripts[i]}"
		ject "${scripts[i]}"

	done
	
fi

# Finally, the install script
if [  $(($PARM&4)) == 4  ]
then
	echo "install script requested:"
	# Check to see if the script is already split (it will be if you injected
	# scripts first) 
	if [ $cnt == 0 ] 
		then
		# echo "Haven't Parsed Yet"
		split-script "${array[0]}"
	fi
	ject "${scripts[0]}"
fi

echo "done"

#This is terrible. I should have written this in python
#or literally anything else.